/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ConnectDB;
import dao.DangNhap;
import io.FileFactory;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.util.Vector;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TrangNguyen
 */
public class DatDV extends javax.swing.JFrame {

    Vector header, data, row;
    Connection con;
    DefaultTableModel dvModel, ddvModel;
    String maHoaDon;
    
    String maDichVu;
    String sldat;

    String ma_dv_cn;
    String sldat_CapNhat;

    public DatDV(java.awt.Frame parent, boolean modal, String maHD, String maPhong) {
        initComponents();
        HienThiUser();
        setTitle("Đặt dịch vụ");
        this.setLocationRelativeTo(null);
        setResizable(false);
        
        txtMaphong.setText(maPhong);
        txtMaphong.setEditable(false);
        btnHuyDV.setEnabled(false);
        btnCapnhap.setEnabled(false);
        maHoaDon = maHD;
        showDV();
        showDDV();
        System.out.println(maHoaDon);
    }


    private void showDV() {
        data = new Vector();
        try {
            con = ConnectDB.getConnect();
            String sql = "select ma_DV, ten_DV, gia, sl_ton from Kho where tinh_trang=0";
            PreparedStatement pstm = con.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("ma_DV"));
                row.add(rs.getString("ten_DV"));
                row.add(rs.getString("gia"));
                row.add(rs.getString("sl_ton"));
                data.add(row);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        dvModel = new DefaultTableModel();
        header = new Vector();
        header.add("Mã DV");
        header.add("Tên DV");
        header.add("Đơn giá");
        header.add("Số lượng tồn");

        dvModel.setDataVector(data, header);
        tblDV.setModel(dvModel);

    }

    public void showDDV() {
        data = new Vector();
        try {
            con = ConnectDB.getConnect();
            String sql = "SELECT dbo.CTHoaDon.ma_HD , dbo.Kho.ma_DV, dbo.Kho.ten_DV,dbo.CTHoaDon.so_luong FROM dbo.CTHoaDon, dbo.Kho WHERE dbo.CTHoaDon.ma_DV = dbo.Kho.ma_DV AND dbo.CTHoaDon.tinh_trang = '0' AND dbo.CTHoaDon.ma_HD = ?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, maHoaDon);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                data.add(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        ddvModel = new DefaultTableModel();
        header = new Vector();
        header.add("Mã Hóa Đơn");
        header.add("Mã Dịch Vụ");
        header.add("Tên Dịch Vụ");
        header.add("Số lượng đặt");

        ddvModel.setDataVector(data, header);
        tblDDV.setModel(ddvModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMaphong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDV = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDDV = new javax.swing.JTable();
        btnHuyDV = new javax.swing.JButton();
        btnDV = new javax.swing.JButton();
        btnCapnhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtSoluong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(182, 182, 233));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText(" DỊCH VỤ");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Mã Phòng");

        txtMaphong.setEditable(false);
        txtMaphong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(51, 51, 255))); // NOI18N

        tblDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã DV", "Tên DV", "Đơn giá", "Số lượng tồn"
            }
        ));
        tblDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDV);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết DV đã đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 51, 255))); // NOI18N

        tblDDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đơn đặt phòng", "Mã dịch vụ", "Số lượng đặt"
            }
        ));
        tblDDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDDVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDDV);

        btnHuyDV.setText("Hủy DV");
        btnHuyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDVActionPerformed(evt);
            }
        });

        btnDV.setText("Đặt DV");
        btnDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDVActionPerformed(evt);
            }
        });

        btnCapnhap.setText("Cập nhập DV");
        btnCapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhapActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thoat.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số Lượng Đặt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(btnHuyDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(btnDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(btnHuyDV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public boolean kiemTraTonTai(String maDV){
        try {
            String sql = "select ma_DV from CTHoaDon where ma_DV = ? and ma_HD = ?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, maDV);
            pstm.setString(2, maHoaDon);
            ResultSet rs = pstm.executeQuery();
            if (rs.next()) {
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
     
    private void btnDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDVActionPerformed
//        System.out.println(txtSoluong.getText());
        if (kiemTraTonTai(maDichVu)) {
            JOptionPane.showMessageDialog(null, "Dịch Vụ Đã được đặt .");
            return;
        }
       
        if (txtSoluong.getText().equals("") || txtSoluong.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Nhập số lượng dịch vụ ");
            txtSoluong.setText("");
            txtSoluong.requestFocus();
            return;
        }
        if (!txtSoluong.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Số lượng đặt phải là chữ số ");
            txtSoluong.setText("");
            txtSoluong.requestFocus();
            return;
        }
        
        try {
            String sql = "insert into CTHoaDon values(?,?,?,?)";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, maHoaDon);
            pstm.setString(2, maDichVu);
            pstm.setString(3, txtSoluong.getText());
            pstm.setString(4, "0");
            pstm.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        showDDV();
    }//GEN-LAST:event_btnDVActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

String solt;
    private void tblDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDVMouseClicked
        showDDV();
        btnDV.setEnabled(true);
        btnHuyDV.setEnabled(false);
        btnCapnhap.setEnabled(false);
        txtSoluong.setText("");
        int soDong = tblDV.getSelectedRow();
        maDichVu = (String) tblDV.getValueAt(soDong, 0);
        solt = (String) tblDV.getValueAt(soDong, 3);
        sldat = txtSoluong.getText();
        System.out.println(maDichVu);
            
    }//GEN-LAST:event_tblDVMouseClicked

    private void btnCapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhapActionPerformed
        if (txtSoluong.getText().equals("") || txtSoluong.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Nhập số lượng dịch vụ ");
            txtSoluong.setText("");
            txtSoluong.requestFocus();
            return;
        }
        if (!txtSoluong.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Số lượng đặt phải là chữ số ");
            txtSoluong.setText("");
            txtSoluong.requestFocus();
            return;
        }

        try {
            String sql = "update CTHoaDon set so_luong = ? where CTHoaDon.ma_DV = ? ";

            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txtSoluong.getText());
            pstm.setString(2, ma_dv_cn);
            pstm.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        showDDV();
    }//GEN-LAST:event_btnCapnhapActionPerformed

    private void tblDDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDDVMouseClicked
        showDV();
        btnDV.setEnabled(false);
        btnHuyDV.setEnabled(true);
        btnCapnhap.setEnabled(true);
        int soDong = tblDDV.getSelectedRow();
        ma_dv_cn = (String) tblDDV.getValueAt(soDong, 1);
        txtSoluong.setText((String)tblDDV.getValueAt(soDong, 3));
//        try {
//            con = ConnectDB.getConnect();
//            String sql = "select ma_CTHD from CTHoaDon where ma_DV = ?";
//            PreparedStatement pstm = con.prepareStatement(sql);
//            pstm.setString(1, ma_dv_cn);
//            ResultSet rs = pstm.executeQuery();
//            while (rs.next()) {
//                System.out.println(rs.getString(1));
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_tblDDVMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        dispose();
        MenuChinh menuchinh = new MenuChinh(tenDN,hoTen,quyen,matkhau);
        menuchinh.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnHuyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDVActionPerformed
        int ret = JOptionPane.showConfirmDialog(null, "Chắc Chắn Hủy Dịch Vụ ", "Dịch Vụ", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            String sql = "update CTHoaDon set tinh_trang = 1 where CTHoaDon.ma_DV = ? ";

            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, ma_dv_cn);
            pstm.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        showDDV();
        txtSoluong.setText("");
    }//GEN-LAST:event_btnHuyDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


 /* Create and display the form */
   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatDV dialog = new DatDV(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhap;
    private javax.swing.JButton btnDV;
    private javax.swing.JButton btnHuyDV;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblDDV;
    private javax.swing.JTable tblDV;
    private javax.swing.JTextField txtMaphong;
    private javax.swing.JTextField txtSoluong;
    // End of variables declaration//GEN-END:variables
String tenDN,hoTen,quyen,matkhau;
    private void HienThiUser() {
        File file = new File("data.data");
        if (file.exists()) {
            Object data = FileFactory.ReadData("data.data");
            if (data != null) {
                DangNhap dn = (DangNhap) data; // ép kiểu về dạng đối tượng
                tenDN = dn.getTen();
                hoTen = dn.getHoten();
                quyen = dn.getQuyen();
                matkhau = dn.getMatkhau();
            }
        }
    }
}
