/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ConnectDB;
import dao.ConnectDB;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nhandang
 */
public class DoiMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhaua
     */
    Icon icon = new ImageIcon(getClass().getResource("/image/warning.png"));
    Icon iconSuccess = new ImageIcon(getClass().getResource("/image/success.png"));
    Icon iconQ = new ImageIcon(getClass().getResource("/image/question.png"));
    String mk_, tendn;

    public DoiMatKhau(java.awt.Frame parent, boolean modal, String tendangnhap, String hoten, String matkhau) {
        super(parent, modal);
        initComponents();
        this.setTitle("Mật Khẩu ");
        this.setLocationRelativeTo(null);
        setResizable(false);

        this.hoten.setText(hoten);
        this.txtTeNDangNhap.setText(tendangnhap);
        this.txtTeNDangNhap.setEditable(false);
        mk_ = matkhau;
        tendn = tendangnhap;
        //viet ham xu ly
        btnDoiMatKhau.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doiMatKhau();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ten = new javax.swing.JLabel();
        mk = new javax.swing.JLabel();
        mkn = new javax.swing.JLabel();
        xn = new javax.swing.JLabel();
        btnDoiMatKhau = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtXacNhan = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMKHienTai = new javax.swing.JPasswordField();
        txtTeNDangNhap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        iconTenDangNhap = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ten.setText("Tên Đăng Nhập");

        mk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mk.setText("Mật Khẩu Hiện Tại");

        mkn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mkn.setText("Mật Khẩu Mới");

        xn.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        xn.setText("Xác Nhận");

        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doimatkhau1.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thoat.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtXacNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtXacNhanKeyPressed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));

        iconTenDangNhap.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        iconTenDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTenDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accinfo.png"))); // NOI18N

        hoten.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        hoten.setForeground(new java.awt.Color(0, 102, 102));
        hoten.setText("Đặng Hữu Nhân");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(iconTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoten, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(mkn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mk, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeNDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtMKHienTai)
                            .addComponent(txtMatKhauMoi)
                            .addComponent(txtXacNhan)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDoiMatKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtTeNDangNhap)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMKHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mkn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtXacNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXacNhanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            doiMatKhau();
        }
    }//GEN-LAST:event_txtXacNhanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhau dialog = new DoiMatKhau(new javax.swing.JFrame(), true, null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel hoten;
    private javax.swing.JLabel iconTenDangNhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mk;
    private javax.swing.JLabel mkn;
    private javax.swing.JLabel ten;
    private javax.swing.JPasswordField txtMKHienTai;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JTextField txtTeNDangNhap;
    private javax.swing.JPasswordField txtXacNhan;
    private javax.swing.JLabel xn;
    // End of variables declaration//GEN-END:variables

    private void doiMatKhau() {
        String mkHienTai = new String(txtMKHienTai.getPassword());
        if (!mkHienTai.trim().equals(mk_)) {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Hiện Tại Không Chính Xác", "Mật Khẩu", JOptionPane.WARNING_MESSAGE, icon);
            txtMKHienTai.setText("");
            txtMatKhauMoi.setText("");
            txtXacNhan.setText("");
            txtMKHienTai.requestFocus();
            return;
        }
        // xu ly mat khau moi
        if (txtMatKhauMoi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Không Thể Trống", "", JOptionPane.OK_OPTION, icon);
            txtMatKhauMoi.requestFocus();
            return;
        }

        if (txtMatKhauMoi.getText().length() > 100) {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Không Thể Lớn Hơn 100 Ký Tự", "", JOptionPane.OK_OPTION, icon);
            txtMatKhauMoi.setText("");
            txtMatKhauMoi.requestFocus();
            return;
        }
        if (txtMatKhauMoi.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Phải Lớn Hơn 3 Ký Tự", "", JOptionPane.OK_OPTION, icon);
            txtMatKhauMoi.setText("");
            txtMatKhauMoi.requestFocus();
            return;
        }
        if (!(txtMatKhauMoi.getText().trim().matches("[a-zA-Z0-9_]{3,100}"))) {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Phải Là Ký Tự Hoặc Số", "", JOptionPane.OK_OPTION, icon);
            txtMatKhauMoi.setText("");
            txtMatKhauMoi.requestFocus();
            return;
        }
        if (!(txtMatKhauMoi.getText().equals(txtXacNhan.getText()))) {
            JOptionPane.showMessageDialog(null, "Xác Nhận Chính Xác Mật Khẩu Mới", "Mật Khẩu", JOptionPane.WARNING_MESSAGE, icon);
            return;
        }
        if (txtMatKhauMoi.getText().equals(txtMKHienTai.getText())) {
            JOptionPane.showMessageDialog(null, "Cập Nhật Thất Bại", "Mật Khẩu", JOptionPane.WARNING_MESSAGE, icon);
            return;
        }
        try {
            Connection con = ConnectDB.getConnect();
            String sql = "update TaiKhoan set mat_khau = ? where ten_dn = ?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txtMatKhauMoi.getText().trim());
            pstm.setString(2, tendn);
            int result = pstm.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Đổi Mật Khẩu Thành Công", "Mật Khẩu", JOptionPane.INFORMATION_MESSAGE, iconSuccess);
                dispose();
                int ret = JOptionPane.showConfirmDialog(null, "Vui Lòng Khởi Động Lại Chương Trình", "System", JOptionPane.OK_OPTION, JOptionPane.WARNING_MESSAGE, iconQ);
                if (ret == JOptionPane.NO_OPTION || ret == JOptionPane.CLOSED_OPTION) {
                    return;
                }
                Runtime objR = Runtime.getRuntime();
                objR.exec("E:\\KARAOKE_WinWin\\dist\\KARAOKE_WinWin.exe ");
                
                MenuChinh menuChinh = new MenuChinh("", "", "", "");
                menuChinh.exitSystem();

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
