package gui;

import dao.ConnectDB;
import dao.DangNhap;
import io.FileFactory;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class QLPhong extends javax.swing.JFrame {

    DefaultTableModel pModel;
    Vector header, data, row;
    Connection con;
    Statement stmt;
    ResultSet rs;
    String sql;
    int dong;
    String ma, loai, loaiStr, nhan, tt = "0", ttStr, gia;
    String where = "where tinh_trang < '3'";

    public QLPhong() {
        initComponents();
        HienThiUser();
        showTable();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void showTable() {
        data = new Vector();
        try {
            con = ConnectDB.getConnect();
            stmt = con.createStatement();
            sql = "select ma_phong, loai_phong, gia, case tinh_trang when 0 then N'Trống' when 1 then N'Đã đặt' when 2 then N'Sửa chửa' end as tinh_trang from DMPhong " + where + "";
            // 0 = Trong, 1 = Da dat, 2 = Sua chua, 3 = Xoa
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("ma_phong"));
                row.add(rs.getString("loai_phong"));
                row.add(rs.getString("gia").replace(".000", ""));
                row.add(rs.getString("tinh_trang"));
                data.add(row);
            }
        } catch (SQLException e) {
        }

        pModel = new DefaultTableModel();
        header = new Vector();
        header.add("Mã phòng");
        header.add("Loại phòng");
        header.add("Giá");
        header.add("Tình trạng");

        pModel.setDataVector(data, header);
        tbPhong.setModel(pModel);

        setEnField(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    
    private void setEnField(boolean check) {
        txtMa.setEnabled(check);
        txtGia.setEnabled(check);
        cbTt.setEnabled(check);
        cbLoai.setEnabled(check);
    }

    private void setEdField(boolean check) {
        txtMa.setEditable(check);
        txtGia.setEditable(check);
    }

    private void clearField() {
        txtMa.setText("");
        txtGia.setText("");
        cbTt.setSelectedIndex(0);
        cbLoai.setSelectedIndex(0);
    }

    private void setModelT(String mot, String hai, String ba) {
        Vector v = new Vector();
        if (!mot.isEmpty()) {
            v.add(mot);
        }
        if (!hai.isEmpty()) {
            v.add(hai);
        }
        if (!ba.isEmpty()) {
            v.add(ba);
        }
        cbTt.setModel(new DefaultComboBoxModel(v));
    }
    
    private void setModelL(String mot, String hai) {
        Vector v = new Vector();
        if (!mot.isEmpty()) {
            v.add(mot);
        }
        if (!hai.isEmpty()) {
            v.add(hai);
        }
        cbLoai.setModel(new DefaultComboBoxModel(v));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cbLoai = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cbTk = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbTt = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhong = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý phòng hát");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã phòng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Giá phòng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Loại phòng");

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng Thường", "Phòng Vip" }));
        cbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiItemStateChanged(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tìm kiếm phòng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        cbTk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----***-----", "Trống", "Đã đặt", "Sửa chửa" }));
        cbTk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTkItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbTk, javax.swing.GroupLayout.Alignment.TRAILING, 0, 126, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbTk)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tình trạng");

        cbTt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Sửa chửa" }));
        cbTt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTtItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtMa))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnThem)
                        .addGap(52, 52, 52)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbLoai, cbTt, txtGia, txtMa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbTt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbLoai, cbTt, txtGia, txtMa});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phòng hát", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhong);

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thoat.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhongMouseClicked
        dong = tbPhong.getSelectedRow();
        ma = (String) pModel.getValueAt(dong, 0);
        loai = (String)pModel.getValueAt(dong, 1);
        gia = (String) pModel.getValueAt(dong, 2);
        tt = (String)pModel.getValueAt(dong, 3);
        
        if (tt.equals("Đã đặt")) {
            setModelT("Đã đặt", "", "");
            setEnField(true);
            setEdField(false);
            btnSua.setText("Sửa");
            btnThem.setText("Thêm");
            btnSua.setEnabled(false);
            btnThem.setEnabled(true);
            btnXoa.setEnabled(false);
        } else {
            if (tt.equals("Trống")) {
                setModelT("Trống", "", "");
            } else {
                setModelT("Sửa chửa", "", "");
            }
            setEnField(true);
            setEdField(false);
            btnSua.setText("Sửa");
            btnThem.setText("Thêm");
            btnSua.setEnabled(true);
            btnThem.setEnabled(true);
            btnXoa.setEnabled(true);
        }
        
        if (loai.equals("Phòng Thường")) {
            setModelL("Phòng Thường", "");
        } else {
            setModelL("Phòng Vip", "");
        }
        
        System.out.println(tt);
        txtMa.setText(ma);
        txtGia.setText(gia);
    }//GEN-LAST:event_tbPhongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        setModelT("Trống", "", "");
        nhan = btnThem.getText();
        if (nhan.equals("Thêm")) {
            btnThem.setText("Lưu");
            clearField();
            setEnField(true);
            cbTt.setEnabled(false);
            setEdField(true);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            txtMa.grabFocus();
        } else {
            ma = txtMa.getText().trim();
            loai = cbLoai.getSelectedItem().toString();
            gia = txtGia.getText();
            
            if (ma.isEmpty() || gia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống !");
                return;
            }

            try {
                con = ConnectDB.getConnect();
                stmt = con.createStatement();
                sql = "select ma_phong from DMPhong";
                rs = stmt.executeQuery(sql);
                
                while (rs.next()) {
                String ma_p = rs.getString("ma_phong");
                
                    if (ma.equals(ma_p)) {
                        JOptionPane.showMessageDialog(this, "Mã phòng đã có sẵn !");
                        return;
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            
            if (!ma.matches("[a-zA-z0-9]{2,30}")) {
                JOptionPane.showMessageDialog(this, "Mã phòng không hợp lệ !");
                txtMa.grabFocus();
                return;
            }
            
            if (!gia.matches("[0-9]{3,19}")) {
                JOptionPane.showMessageDialog(this, "Giá chỉ được nhập số");
                return;
            }

            sql = "Insert into DMPhong(ma_phong, loai_phong, gia, tinh_trang) values('" + ma + "', N'" + loai + "', " + gia + ", " + tt + ")";
            try {
                stmt.executeUpdate(sql);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            clearField();
            setEnField(false);
            setEdField(false);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            btnThem.setText("Thêm");
            showTable();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        ttStr = (String)pModel.getValueAt(tbPhong.getSelectedRow(), 3);
        if (ttStr.equals("Trống")) {
                setModelT("", "Trống", "Sửa chửa");
            } else {
                setModelT("", "Sửa chửa", "Trống");
        }
        
        loaiStr = (String)pModel.getValueAt(tbPhong.getSelectedRow(), 1);
        if (loaiStr.equals("Phòng Thường")) {
                setModelL("Phòng Thường", "Phòng Vip");
            } else {
                setModelL("Phòng Vip", "Phòng Thường");
        }
        
        nhan = btnSua.getText();
        if (nhan.equals("Sửa")) {
            tt = cbTt.getSelectedItem().toString();
            if (tt.equals("Trống")) {
                tt = "0";
            } else {
                tt = "2";
            }
            loai = cbLoai.getSelectedItem().toString();
            if (loai.equals("Phòng Thường")) {
                loai = "Phòng Thường";
            } else {
                loai = "Phòng Vip";
            }
            
            btnSua.setText("Lưu");
            setEnField(true);
            setEdField(true);
            txtMa.setEditable(false);
            btnThem.setEnabled(false);
            btnXoa.setEnabled(false);
            txtMa.grabFocus();
        } else {
            ma = txtMa.getText();
            gia = txtGia.getText();
            
            if (ma.isEmpty() || gia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống !");
                return;
            }

            if (gia.matches("\\d")) {
                JOptionPane.showMessageDialog(this, "Giá chỉ được nhập số");
                return;
            }

            try {
                con = ConnectDB.getConnect();
                stmt = con.createStatement();
                stmt.executeUpdate("update DMPhong set loai_phong = N'" + loai + "', gia = '" + gia + "', tinh_trang = "+ tt +" where ma_phong = '" + ma + "'");
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearField();
            setEnField(false);
            setEdField(false);
            btnThem.setEnabled(true);
            btnXoa.setEnabled(true);
            btnSua.setText("Sửa");
            showTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cbTtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTtItemStateChanged
        if (cbTt.getSelectedItem() == "Trống") {
            tt = "0";
        }
        if (cbTt.getSelectedItem()== "Sửa chửa") {
            tt = "2";
        }
    }//GEN-LAST:event_cbTtItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Detele?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        dong = tbPhong.getSelectedRow();

        ma = (String) pModel.getValueAt(dong, 0);

        if (result == JOptionPane.YES_OPTION) {
            pModel.removeRow(dong);
            try {
                con = ConnectDB.getConnect();
                stmt = con.createStatement();
                stmt.executeUpdate("update DMPhong set tinh_trang = '3' where ma_phong = '" + ma + "'");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        clearField();
        setEnField(false);
        setEdField(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        showTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbTkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTkItemStateChanged
        if (cbTk.getSelectedIndex() == 1) {
            where = "where tinh_trang = '0'";
            showTable();
        }
        if (cbTk.getSelectedIndex() == 2) {
            where = "where tinh_trang = '1'";
            showTable();
        }
        if (cbTk.getSelectedIndex() == 3) {
            where = "where tinh_trang = '2'";
            showTable();
        }
        if (cbTk.getSelectedIndex() == 0) {
            where = "where tinh_trang < '3'";
            showTable();
        }
    }//GEN-LAST:event_cbTkItemStateChanged

    private void cbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiItemStateChanged
        if (cbLoai.getSelectedItem() == "Phòng Thường") {
            loai = "Phòng Thường";
        }
        if (cbLoai.getSelectedItem()== "Phòng Vip") {
            loai = "Phòng Vip";
        }
    }//GEN-LAST:event_cbLoaiItemStateChanged

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        dispose();
        MenuChinh menuchinh = new MenuChinh(tenDN,hoTen,quyen,matkhau);
        menuchinh.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            QLPhong ql = new QLPhong();
            ql.setVisible(true);
            ql.setLocationRelativeTo(null);
            ql.setTitle("Quản lý phòng hát");
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JComboBox<String> cbTk;
    private javax.swing.JComboBox<String> cbTt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPhong;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables

String tenDN,hoTen,quyen,matkhau;
    private void HienThiUser() {
        File file = new File("data.data");
        if (file.exists()) {
            Object data = FileFactory.ReadData("data.data");
            if (data != null) {
                DangNhap dn = (DangNhap) data; // ép kiểu về dạng đối tượng
                tenDN = dn.getTen();
                hoTen = dn.getHoten();
                quyen = dn.getQuyen();
                matkhau = dn.getMatkhau();
            }
        }
    }
}
